config/routes.rb
# == Route Map
#
#          Prefix Verb URI Pattern                           Controller#Action
#                 GET  /                                     events#index
#           event GET  /events/:id(.:format)                 events#show
#             new GET  /new(.:format)                        events#new
#          events POST /events(.:format)                     events#create
#     create_post POST /events/:event_id/posts(.:format)     posts#create
# create_resource POST /events/:event_id/resources(.:format) resources#create
#        api_ping GET  /api/ping(.:format)                   api#ping
#           login GET  /login(.:format)                      sessions#new
#          logout GET  /logout(.:format)                     sessions#destroy
#                 GET  /auth/:provider/callback(.:format)    sessions#create
#    auth_failure GET  /auth/failure(.:format)               sessions#failure
#

Rails.application.routes.draw do
  get '', :to => 'events#index'
  get 'events/:id', :to => 'events#show', :as => 'event'
  get 'new', :to => 'events#new'
  post 'events', :to => 'events#create'

  post 'events/:event_id/posts', :to => 'posts#create', :as => 'create_post'
  post 'events/:event_id/resources', :to => 'resources#create', :as => 'create_resource'

  get 'api/ping'

  get 'login', :to => 'sessions#new', :as => :login
  get 'logout', :to => 'sessions#destroy', :as => :logout
  get 'auth/:provider/callback', :to => 'sessions#create'
  get 'auth/failure', :to => 'sessions#failure'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  start_date :date
#  end_date   :date
#  user_id    :integer
#  latitude   :float
#  longitude  :float
#  radius     :integer
#  created_at :datetime
#  updated_at :datetime
#

EARTH_RADIUS = 20903520 # feet

def distance(lat1, lng1, lat2, lng2)
  dLat = to_radians(lat2 - lat1)
  dLng = to_radians(lng2 - lng1)

  a = Math.sin(dLat/2) * Math.sin(dLat/2) + 
      Math.cos(to_radians(lat1)) * Math.cos(to_radians(lat2)) *
      Math.sin(dLng/2) * Math.sin(dLng/2)
  c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))

  EARTH_RADIUS * c
end

def to_radians(d)
  d * Math::PI / 180
end

class Event < ActiveRecord::Base
  belongs_to :user
  has_many :posts, -> { order(:created_at => :desc) }
  has_many :resources, -> { order(:created_at => :desc) }

  def self.locate(lat, lng)
    possibles = Event.where("start_date <= ? AND end_date >= ?", Date.today, Date.today)

    possibles.select do |e|
      distance(e.latitude, e.longitude, lat, lng) <= e.radius
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate

  def index
    @old_events = @current_user.events.where("end_date < ?", Date.today)
    @future_events = @current_user.events.where("start_date > ?", Date.today)
    @current_events = @current_user.events.where("start_date <= ? AND end_date >= ?", Date.today, Date.today)
  end

  def show
    @event = Event.find_by(id: params[:id])

    if @event.user != @current_user
      redirect_to "/"
    end
  end

  def new
  end

  def create
    name = params[:name]
    start_date = params[:start_date]
    end_date = params[:end_date]
    latitude = params[:latitude].to_f
    longitude = params[:longitude].to_f
    radius = params[:radius].to_i

    if name != "" && start_date != "" && end_date != ""
      @event = Event.new({
        name: name,
        start_date: start_date,
        end_date: end_date,
        latitude: latitude,
        longitude: longitude,
        radius: radius
      })

      @event.user = @current_user
      @event.save

      redirect_to event_path(@event)
    else
      redirect_to "/new"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h1>Active Events</h1>
<% unless @current_events.empty? %>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Posts</th>
				<th>Resources</th>
			</tr>
		</thead>
		<tbody>
			<% @current_events.each do |event| %>
				<tr class="event-row" data-href="<%= event_path(event) %>">
					<td><%= event.name %></td>
					<td><%= event.start_date.to_formatted_s(:long) %></td>
					<td><%= event.end_date.to_formatted_s(:long) %></td>
					<td><%= event.posts.count %></td>
					<td><%= event.resources.count %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>None</p>
<% end %>

<hr />

<h1><small>Future Events</small></h1>
<% unless @future_events.empty? %>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Posts</th>
				<th>Resources</th>
			</tr>
		</thead>
		<tbody>
			<% @future_events.each do |event| %>
				<tr class="event-row" data-href="<%= event_path(event) %>">
					<td><%= event.name %></td>
					<td><%= event.start_date.to_formatted_s(:long) %></td>
					<td><%= event.end_date.to_formatted_s(:long) %></td>
					<td><%= event.posts.count %></td>
					<td><%= event.resources.count %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>None</p>
<% end %>

<hr />

<h1><small>Past Events</small></h1>
<% unless @old_events.empty? %>
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Start Date</th>
				<th>End Date</th>
				<th>Posts</th>
				<th>Resources</th>
			</tr>
		</thead>
		<tbody>
			<% @old_events.each do |event| %>
				<tr class="event-row" data-href="<%= event_path(event) %>">
					<td><%= event.name %></td>
					<td><%= event.start_date.to_formatted_s(:long) %></td>
					<td><%= event.end_date.to_formatted_s(:long) %></td>
					<td><%= event.posts.count %></td>
					<td><%= event.resources.count %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>None</p>
<% end %>

app/views/events/new.html.erb
<h2>New Event</h2>
<div class="row">
	<div class="col-md-4">
		<%= form_tag("/events", method: "post") do %>
			<div class="form-group">
				<label for="name">Name:</label>
				<input type="text" name="name" class="form-control" placeholder="My cool event" id="name">
			</div>
			<div class="form-group">
				<label for="from">From:</label>
				<input type="date" name="start_date" class="form-control" id="from">
			</div>
			<div class="form-group">
				<label for="end">To:</label>
				<input type="date" name="end_date" class="form-control" id="end">
			</div>

			<input type="hidden" name="latitude" id="latitude">
			<input type="hidden" name="longitude" id="longitude">
			<input type="hidden" name="radius" id="radius">

			<button type="submit" class="btn btn-primary btn-blo btn-submit">Create Event</button>
		<% end %>
	</div>
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-6">
				<form role="form" id="address" action="javascript:codeAddress()">
					<div class="form-group">
						<label for="address">Search:</label>
							<div class="input-group">
							<div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
							<input placeholder="Address" type="search" class="form-control">
						</div>
					</div>
				</form>
			</div>

			<div class="col-md-6">
				<form role="form-" id="radius-form" action="javascript:codeRadius()">
					<div class="form-group">
						<label for="radius">Radius:</label>
						<div class="input-group">
							<input placeholder="Radius" type="number" class="form-control">
							<div class="input-group-addon">feet</div>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div id="map-canvas"></div>
	</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<h4><%= @event.start_date.to_formatted_s(:long) %> to <%= @event.end_date.to_formatted_s(:long) %></h4>

<hr class="no-margin" />

<div class="row">
	<div class="col-md-6">
		<h3>Updates</h3>

		<%= form_tag create_post_path(@event), :method => :post, :class => 'clearfix' do %>
			<div class="form-group">
				<label for="end">New update:</label>
				<textarea class="form-control" rows="3" name="text"></textarea>
			</div>

			<button type="submit" class="btn btn-primary btn-blo btn-submit">Post</button>
		<% end %>

		<hr />

		<dl class="">
		<% @event.posts.each do |post| %>
			<dt><%= post.created_at.in_time_zone.to_formatted_s(:long) %></dt>
			<dd><p><%= post.text %></p></dd>
		<% end %>
		</dl>
	</div>
	<div class="col-md-6">
		<h3>Resources</h3>

		<%= form_tag create_resource_path(@event), :method => :post, :class => 'clearfix' do %>
			<div class="form-group form-inline">
				<label for="end">New resource:</label>
				<p class="form-control-static" id="file_name_static"></p>
				<input type="hidden" name="name" id="name">
				<input type="hidden" name="file_id" id="file_id">
				<a href="#" id="image-pick-link">(Pick file)</a>
			</div>

			<button type="submit" class="btn btn-primary btn-blo btn-submit">Post</button>
		<% end %>

		<hr />

		<dl class="">
			<% @event.resources.each do |resource| %>
				<dt><%= resource.created_at.in_time_zone.to_formatted_s(:long) %></dt>
				<% if resource.url %>
					<dd><p><a href="<%= resource.url %>"><%= resource.name %></p></a></dd>
				<% else %>
					<dd><p><%= resource.name %></p></dd>
				<% end %>
			<% end %>
		</dl>
	</div>
</div>

<script>
myAuthToken = "<%= @current_user.token %>"
</script>